name = "SupremeWarfare4k"
version = 1.0
copyright = "Copyright © 2022 Illumination"
author = "Illumination"
description = "The war has been evolved . Time to embrace your destruction ! "
uid = "4188DBD9-F325-5D6E-DFA9-866A27CB92DF"
exclusive = false
ui_only = false
selectable = true
requires = {'xd70mmk546-ac36-4c20-825d-uis-rtc-not', }
icon = "/mods/SupremeWarfare4k/icon.jpg" 
before = { }
