name = "UI vault"
version = 1
description = "The game constructs itself into fullness basing on multiple phases and sim is a part of which. Uimain.lua is where the Engine learns it and gamemain.lua completes parts of the structure."
author = "Illumination"
uid = "xd70mmk546-ac36-4c20-825d-uis-rtc-not"
selectable = true
exclusive = false
ui_only = false
icon = "/mods/UIvault/icon.png"